### ISSUE TITLE
Still does not work with Python 2 over Putty

### ISSUE THREAD

**Issue by SuperSandro2000** [SteamDatabase/SalienCheat#12]
Script still does not work with Python 2 on my Raspberry Pi 3b over WinSSHTerm (Putty).
````
python cheat.py
Login to steamcommunity.com
Visit https://steamcommunity.com/saliengame/gettoken
Copy the token value and paste here.
---
Token: "xxxxxxxx"
Traceback (most recent call last):
  File "cheat.py", line 241, in <module>
    game.access_token = get_access_token()
  File "cheat.py", line 59, in get_access_token
    fp.write(token)
TypeError: write() argument 1 must be unicode, not str

````

**Comment by Scrxtchy** [comment]
Python3?

**Comment by SuperSandro2000** [comment]
Python 3 works like a charm. maybe mention in the readme.md that it only works with py3.
