### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by JourneyOver** [SteamDatabase/SalienCheat#34]
Recent python script update : https://github.com/SteamDatabase/SalienCheat/commit/e8ad440d2cc0960b9bc3a68e1b40245df64afb63

Loops a few times on getting level and then crashes on 
```
Player Level: 0it [00:00, ?it/s]
Planet progress: 0it [00:00, ?it/s]

                                ]


2018-06-22 15:50:11 | Loaded token from token.txt
Player Level: 0it [00:00, ?it/s]

Zone progress: 0it [00:00, ?it/s]
                                /s]


2018-06-22 15:50:12 | Getting player info...
Player Level: 0it [00:01, ?it/s]

Zone progress: 0it [00:01, ?it/s]
                                /s]


2018-06-22 15:50:12 | Finding planet...
Player Level: 0it [00:01, ?it/s]

Zone progress: 0it [00:01, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:01 Planet progress: 0it [00:00, ?it/s]




2018-06-22 15:50:13 | Found 5 uncaptured planets: [4, 5, 6, 7, 8]
Player Level 10         51% |###############################################################4                                                             |      00:02

Zone  progress: 0it [00:01, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:02 Planet progress: 0it [00:00, ?it/s]




2018-06-22 15:50:15 | Joining planet 8..
Player Level 10         51% |###############################################################4                                                             |      00:03

Zone  progress: 0it [00:01, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:03 Planet progress: 0it [00:00, ?it/s]




2018-06-22 15:50:15 | Planet name: #TerritoryControl_PlanetMold-breaking_Metroidvanias_I (8)
Player Level 10         51% |###############################################################4                                                             |      00:04

Zone  progress: 0it [00:00, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:09




2018-06-22 15:50:15 | Current players: 98370
Player Level 10         51% |###############################################################4                                                             |      00:04

Zone  progress: 0it [00:00, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:09




2018-06-22 15:50:15 | Giveaway AppIDs: [340000, 251730, 201420, 334940]
Player Level 10         51% |###############################################################4                                                             |      00:04

Zone  progress: 0it [00:00, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:09




2018-06-22 15:50:15 | Finding conflict zone...
Player Level 10         51% |###############################################################4                                                             |      00:04

Zone  progress: 0it [00:00, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:09

Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:09




2018-06-22 15:50:15 | Fighting in zone 88 (3) for 2mins
Player Level 10         51% |###############################################################4                                                             |      00:04

Zone  progress: 0it [00:00, ?it/s]
Player Level 10         51% |###############################################################4                                                             |      00:04 Planet (8) progress      8% |##########2                                                                                                                  |      00:10

Zone  progress: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "cheat.py", line 356, in <module>
    for i in range(120 / 2):
TypeError: 'float' object cannot be interpreted as an integer
Exception ignored in: <bound method tqdm.__del__ of Player Level 10         51% |#####     |      00:05>
Traceback (most recent call last):
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 882, in __del__
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 1087, in close
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 439, in _decr_instances
  File "C:\Tools\python3\lib\_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x000001E889C55D18; to 'tqdm' at 0x000001E889C67470>
Exception ignored in: <bound method tqdm.__del__ of Planet (8) progress      8% |8         |      00:18>
Traceback (most recent call last):
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 882, in __del__
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 1087, in close
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 439, in _decr_instances
  File "C:\Tools\python3\lib\_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x000001E889C55D18; to 'tqdm' at 0x000001E889C67BA8>
Exception ignored in: <bound method tqdm.__del__ of Zone  progress: 0it [00:00, ?it/s]>
Traceback (most recent call last):
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 882, in __del__
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 1087, in close
  File "C:\Tools\python3\lib\site-packages\tqdm\_tqdm.py", line 439, in _decr_instances
  File "C:\Tools\python3\lib\_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x000001E889C55D18; to 'tqdm' at 0x000001E889C67C18>
```

**Comment by rossengeorgiev** [comment]
dunno what you are running the code on, but progress bar are displaying wrong

**Comment by JourneyOver** [comment]
Just running it on normal old command prompt on windows 10

**Comment by rossengeorgiev** [comment]
I see. I haven't tried windows native python + cmd. But I wouldn't expect it to work properly. Try using `cmder`, it might get the progress bars to display correctly.

**Comment by JourneyOver** [comment]
cmder outputs it the same way at first, but after the first zone and it starts actually doing the fighting and updating info it starts looking normal. 

The big thing I mainly notice in the python script whenver I do a test run with them are that the timers at the end of the progress stuff is always counting up instead of counting down like the php scripts.
