### ISSUE TITLE
New planet causes error

### ISSUE THREAD

**Issue by tambry** [SteamDatabase/SalienCheat#61]
```
2018-06-23 16:59:55 | Getting player info...
2018-06-23 16:59:55 | Scanning for planets...
Player Level: 0it [00:00, ?it/s]   Traceback (most recent call last):
  File "cheat.py", line 379, in <module>
    planets = game.get_uncaptured_planets()
  File "cheat.py", line 234, in get_uncaptured_planets
    key=lambda x: x['sort_key'],
  File "cheat.py", line 232, in <genexpr>
    return sorted((game.get_planet(p['id']) for p in planets if not p['state']['captured']),
  File "cheat.py", line 185, in get_planet
    key=lambda x: x['zone_position'])
  File "cheat.py", line 183, in <genexpr>
    and z['capture_progress'] < 0.95)),
KeyError: 'capture_progress'
```

**Comment by tambry** [comment]
Fixed by https://github.com/SteamDatabase/SalienCheat/commit/7fb2ccfe8e0236d4a6d5729e844b82022fcc4216
