### ISSUE TITLE
Python version won't accept token

### ISSUE THREAD

**Issue by m3Lith** [SteamDatabase/SalienCheat#8]
Getting this error:

```
Traceback (most recent call last):
  File "cheat.py", line 240, in <module>
    game.access_token = get_access_token()
  File "cheat.py", line 58, in get_access_token
    fp.write(token)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Scrxtchy** [comment]
`<+lz1dev> thats easy to fix`
>not fixed
